### ISSUE TITLE
Issue with Footprint Generation Using ORFD Dataset and PyICP-SLAM

### ISSUE THREAD

**Issue by Hyun-gyu** [yurimjeon1892/FtFoot#1]
Thank you for sharing your great research.

I encountered an issue while trying to generate the footprint using the ORFD dataset. I used PyICP-SLAM to estimate the poses and followed the preprocessing code provided for the ORFD dataset. However, I was unable to generate the footprint.

I suspect the issue might be due to the accuracy of the pose data obtained from PyICP-SLAM. 

I’m wondering if you have experienced a similar problem.

**Comment by yurimjeon1892** [comment]
As you mentioned, the results of PyICP-SLAM were not very accurate. Therefore, it was necessary to manually validate the generated footprints and filter out the usable data.

**Comment by yurimjeon1892** [comment]
Close this issue.

**Comment by Hyun-gyu** [comment]
Sorry for the delayed response. It seems like your answer will be helpful.

By the way, if you have the pose information from ORFD used in the research, could you share it with me?
